name: golang-pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
   # if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v2
      - name: Run Unit Tests
        run: go test
  deploy:
    runs-on: ubuntu-latest
    needs: test
   # if: startsWith(github.ref, 'refs/tags')
    steps:
      - name: DEBUG
        run: |
          echo ${{secrets.DOCKERHUB_USERNAME}}
          echo ${{secrets.DOCKERHUB_TOKEN}}
